### ISSUE TITLE
port ChartObject to GObject

### ISSUE THREAD

**Issue by notmyname** [notmyname/pygtkChart#3]
port the chart object to GObject to allow for more flexibility and things like event handling

**Comment by SvenFestersen** [comment]
ChartObject is now fully ported to GObject. A ChartObject has the properties 'visible' and 'antialias'. The signal 'appearance-changed' is emitted when the object needs to be redrawn.

Classes derived from ChartObject that install own properties have to handle requests for the two properties mentioned above in their do_get_property and do_set_property methods.

Controlling classes (the LineChart widget for example) should connect to the 'appearance-changed' signal and redraw if it's emitted.
