### ISSUE TITLE
LineChart features to add

### ISSUE THREAD

**Issue by SvenFestersen** [notmyname/pygtkChart#7]
The following features should be added to the LineChart widget:

<ul>
<li>a legend of the graphs</li>
<li>possibility to set the datapoint style (point, cross, square, ...) and the line style (solid, dashed, dotted) </li>
<li>option to use logarithmic scale for x- and/or y-axis axes</li>
<li>make datapoints clickable</li>
<li>error bars</li>
</ul>

**Comment by notmyname** [comment]
a few hard-coded datapoint styles may be good, but how possible would it be to have user-supplied icons/pictures/whatever for the datapoint?

**Comment by SvenFestersen** [comment]
Using custom graphics as datapoints is a good idea. That shouldn't be hard to implement.

**Comment by SvenFestersen** [comment]
Done. All features listed above are implemented. Merged branch new_LineChart_features with master.
