### ISSUE TITLE
os independence

### ISSUE THREAD

**Issue by SvenFestersen** [notmyname/pygtkChart#9]
The package should also work on other OS than Linux. Only few lines have to be changed to achieve this (the path separator is hardcoded "/").

**Comment by notmyname** [comment]
I have pushed an os_independence branch that should solve this issue, but I don't have a windows machine to test on. Please verify that this fix works.

**Comment by SvenFestersen** [comment]
I do not have a working Windows installation at the moment too, but I'll install it on a virtual machine to test it.

**Comment by SvenFestersen** [comment]
Done. I had to fix a missing bracket in *_chart.py files, but now the widgets work on Windows without any problems. I'll merge the os_independence branch to master.
